# This is a basic workflow to help you get started with Actions

name: Static Front-end deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Use your bucket region here
        
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./front-end/ s3://jamikal.xyz --delete
      # --delete flag will remove any file in the s3 that are not on the "front-end" folder
